# Generated by Django 4.1.7 on 2023-03-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FailureLogModel',
            new_name='Failure',
        ),
        migrations.RenameModel(
            old_name='ManufacturerModel',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='RegionModel',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='TransformerModel',
            new_name='Transformer',
        ),
    ]
